elife-website:
    vagrant:
        shares:
        -   host: ../elife-website/
            guest: /srv/website
            opts:
                :owner: www-data
                :group: www-data
                :mount_options:
                - dmode=777
                - fmode=777
