defaults:
    aws:
        ami: ami-9cee02f3
        region: eu-central-1
        vpc-id: vpc-0a0ee863
        subnet-id: subnet-29638240
        subnet-cidr: '172.31.16.0/20'
        rds:
            subnets:
                # two are required
                # NOTE! the 'dbsubnet-' prefix is important to *builder*
                # it tells us which subnets we can provision RDS within
                - subnet-3611e55e # dbsubnet-1
                - subnet-78444403 # dbsubnet-2
